version: '3.8'

services:
  eureka-server:
    build:
     args:
        SERVICE_NAME: microservice-eureka
    container_name: eureka-server-TSM
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    #restart: always

networks:
  microservices-net:
    driver: bridge