server:
  port: 8090
spring:
  application:
    name: msvc-catalog
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: catalog
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
