server:
  port: 9090
spring:
  application:
    name: msvc-inventory
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
      hibernate:
        ddl-auto: create
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka